class Config:
    # General
    EPOCHS = 20
    TRAINING_SET_SIZE = 55000  # Full Training Set Size
    
    # Brain Frequency
    BRN_CLEANUP_FREQUENCY = int(TRAINING_SET_SIZE * .25)
    BRN_NEURAL_GROWTH_FREQUENCY = int(TRAINING_SET_SIZE * .3)

    # Cluster
    CLUSTER_REQUIRED_UTILIZATION = int(TRAINING_SET_SIZE * .5)
    CLUSTER_NODE_LEARNING_RATE = 0.02

    # Node
    NODE_REQUIRED_UTILIZATION = int(TRAINING_SET_SIZE * 1.01)
    NODE_POSITION_LEARNING_RATE = 0.04
    NODE_POSITION_MOMENTUM_DECAY = 0.5
    NODE_POSITION_MOMENTUM_ALPHA = 0.0
    NODE_TO_CLUSTER_LEARNING_RATE = 0.05
    NODE_IS_NEW = 25
    NODE_CERTAINTY_AGE_FACTOR = NODE_IS_NEW

    # Node Manager
    NRND_OPTIMIZER_ENABLED = True
    NRND_BUILD_FREQUENCY = int(TRAINING_SET_SIZE / 10)
    NRND_N_TREES = 50
    NRND_SEARCH_K = NRND_N_TREES * 5
    NRND_MAX_AVG_DISTANCE_MOMENTUM = 1e50
    AVG_DISTANCE_MOMENTUM_DECAY = 0.5
    MAX_NODES = 6000
    INITIAL_NODES = 0 # TKBA starts from 0 and grows
    NODE_SPLIT_MAX_CORRELATION_VARIANCE = 5e-3
    NODE_SPLIT_MAX_QTY = max(int(TRAINING_SET_SIZE / 1000), 5)

    # TKBA Settings
    TKBA_VISUAL_SIGMA = 0.15     
    TKBA_VISUAL_VIGILANCE = 0.45 
    
    # Audio (FSDD):
    TKBA_AUDIO_SIGMA = 0.15      
    TKBA_AUDIO_VIGILANCE = 0.45  
    
    TKBA_KBR_SIGMA = 1.0
    
    # CDZ
    CE_LEARNING_RATE = 0.02
    CE_IGNORE_GAUSSIAN = True
    CE_CORRELATION_WINDOW_STD = 0.65
    CE_CORRELATION_WINDOW_MAX = 10
    CE_CERTAINTY_AGE_FACTOR = NODE_CERTAINTY_AGE_FACTOR

    # Autoencoder Training
    # Fixed dimensions to match input data: MNIST(784), FSDD(4096)
    MNIST_LAYERS = [784, 512, 256, 128] 
    FSDD_LAYERS = [4096, 1024, 256, 64] 
    AE_LEARNING_RATE = 1e-3
    AE_BATCH_SIZE = 64
    AE_EPOCHS_MNIST = 100 
    AE_EPOCHS_FSDD = 150 